defenses:
  - defense: Mean
  - defense: SimpleClustering
  - defense: Krum
    defense_params:
      enable_check: false
  - defense: MultiKrum
    defense_params:
      avg_percentage: 0.2
      enable_check: false
  - defense: TrimmedMean
    defense_params:
      beta: 0.1
  - defense: Median
  - defense: Bulyan
    defense_params:
      enable_check: false
  - defense: RFA
    defense_params:
      num_iters: 3
      epsilon: 1.0e-6
  - defense: FLTrust
    defense_params:
      num_sample: 100
  - defense: CenteredClipping
    defense_params:
      norm_threshold: 100
      num_iters: 1
  - defense: DnC
    defense_params:
      subsample_frac: 0.2
      num_iters: 1
      fliter_frac: 1.0
  - defense: Bucketing
    defense_params:
      bucket_size: 2
      selected_aggregator: Krum
  - defense: SignGuard
    defense_params:
      lower_bound: 0.1
      upper_bound: 3.0
      selection_fraction: 0.1
      clustering: MeanShift
      random_seed: 2
  - defense: TriGuardFL
    defense_params:
      cos_threshold: 0.0
      cos_filter_method: mad
      cos_significance: 0.02
      significance: 0.02
      discount: 0.9
      reputation_threshold: 0.6
      epochs_phase_2: 20
      num_items_test: 512
      eval_batch_size: 128
  - defense: Auror
    defense_params:
      indicative_threshold: 7.0e-5
      indicative_find_epoch: 10
  - defense: FoolsGold
    defense_params:
      epsilon: 1.0e-5
      topk_ratio: 0.1
  - defense: NormClipping
    defense_params:
      weakDP: true
      norm_threshold: 3
      noise_mean: 0
      noise_std: 0.002
  - defense: CRFL
    defense_params:
      norm_threshold: 3
      noise_mean: 0
      noise_std: 0.001
  - defense: DeepSight
    defense_params:
      num_seeds: 3
      threshold_factor: 0.01
      num_samples: 20000
      tau: 0.33
      epsilon: 1.0e-6
  - defense: FLAME
    defense_params:
      gamma: 1.2e-5
