attacks:
  - attack: NoAttack
  - attack: IPM
    attack_params:
      scaling_factor: 0.5
  - attack: ALIE
  - attack: Gaussian
    attack_params:
      noise_mean: 0
      noise_std: 1
  - attack: Mimic
    attack_params:
      choice: 0
  - attack: MinMax
    attack_params:
      gamma_init: 10
      stop_threshold: 1.0e-5
  - attack: MinSum
    attack_params:
      gamma_init: 10
      stop_threshold: 1.0e-5
  - attack: FangAttack
    attack_params:
      stop_threshold: 1.0e-5
