seed: 42
num_experiments: 1
experiment_id: 0

epochs: 300
algorithm: FedSGD
optimizer: SGD
momentum: 0.9
weight_decay: 5.0e-4

num_clients: 20
batch_size: 64
learning_rate: 0.05

model: resnet18
dataset: CINIC10
distribution: iid
im_iid_gamma: 0.01
tail_cls_from: 4
dirichlet_alpha: 0.5
cache_partition: false
gpu_idx: [0]
num_workers: 0
record_time: false
log_stream: true

num_adv: 0.2
attack: NoAttack
defense: Mean

catalogs:
  attacks: vision
  defenses: vision
